### ISSUE TITLE
Messenger comparison: add signal and wire

### ISSUE THREAD

**Issue by erotavlas85** [JayXT/MessengerComparison#18]
Hi,
I found your detailed comparison between three of the most common messenger. I would like suggest you to add signal messenger and wire to the comparison. If you want I can contribute to the english version.

**Comment by JayXT** [comment]
Hi erotavlas85,

When I was starting this project, I carefully considered most of the available messenger options, but the final decision was to include only these three. This way it's relatively easy to maintain, update information and to translate pages into different languages. 
Besides, the primary reason why the table was created is because of how much Telegram was ahead of other competitors in a lot of areas, despite the smaller userbase. I wanted to show the world all numerous advantages of Telegram and why it is worthy to switch to it. At the same time Signal and Wire are way less popular and in a nutshell don't offer any prominent advantages over Viber or WhatsApp except higher level of privacy and security at the cost of convenience.
All the same, this project is open-source and if you're really eager to include other messengers you can create your own fork by following recommendations from the description:

**Independent Project**: create a fork of JayXT/MessengerComparison repository, remove redundant translations, update README.md accordingly and continue restructuring the project to serve your purposes (e.g. comparing different set of messengers). If your page contains more then ~25% of original text, markup or CSS styles, please include reference to this repository in your pages to show that your project reuses the developments of JayXT/MessengerComparison.

Thank you for your interest.
