### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by leonheess** [JayXT/MessengerComparison#20]
I agree that Telegram is the #1 messenger. I still think your website would be more effective and convincing if you would try to eliminate some bias by

• replacing all sources linked to one of the companies (like the telegraph blog) and instead cite credible independent news sources
• backing up claims with independent sources or removing them (e.g. I agree that the Telegram privacy policy is far more readable than WhatsApp's but I still think this should either be quantified by you somehow or, even better, by a independent tool/analysis. Same goes for the sending speed. Otherwise it just seems like your opinion instead of a fact and therefore hurts the credibility of the comparison)

**Comment by JayXT** [comment]
Hi leonhees, thank you for your interest in the project. 

I see what you mean, nonetheless regarding your observations: 
1) Telegraph website is an open platform for web-publishing developed by Telegram team, but available for everyone to use on its own or to integrate with services other than Telegram. I guess you meant actual authors of articles, but even here I see nothing wrong in providing materials that reference trustworthy sources. But if there were some better articles that could compete with Parcel Durov's or other author eloquency, precision of statements and brevity of writing style, surely I'd link such. 
2) In terms of proofs and links to sources I use official ones not only for Telegram, but for Viber and WhatsApp as well. The only difference is that Telegram has more official, useful info which is of higher quality too. Regarding sending speed, it was measured manually several times by myself. Maybe in the future, I'll consider creating a YouTube video with similar experiment. For now, users can install any of these apps and check whether the statement is true themselves. Unfortunately, not everything could be easily measured, sometimes it's better to let the users see the difference personally. For instance, privacy policy simplicity is not only about the size, but also about the previously mentioned writing style and clarity. To get the better idea of criteria and why it was considered as advantage, mediocrity or disadvantage, sometimes more useful is to allow users to experience it on their own. My task is to bring people's attention to each criteria, so that they could see the difference and then look into it deeper if they want.

In any event, it's a good trait to doubt and put to the test any content published on the web, so your thoughts are understandable and I analyze and take into account such opinions. From time to time, people discover mistakes or inaccuracies and then I make necessary adjustments.
