### ISSUE TITLE
New messengers

### ISSUE THREAD

**Issue by qweered** [JayXT/MessengerComparison#32]
How about to add Signal, Facebook messenger and ICQ to comparison?

**Comment by JayXT** [comment]
I try to keep the list of messengers for comparison as short as possible due to maintainability concerns. That's why I've compared Telegram with just Viber and WhatsApp, its main competitors. 
Signal was not included due to way smaller number of active users and feature-wise similarity with WhatsApp. Basically Signal mostly could be considered as a more secure and private messenger than WhatsApp, but in terms of other features Signal is basically a subset of WhatsApp. 
Facebook Messenger, despite its gigantic userbase  wasn't included due to serious privacy concerns and scandals around Facebook company (Cambridge Analytica, etc.). To put it simple it's better to stay away from Facebook products, since they are rarely positioned as secure and privacy-respecting solutions. Keep in mind  that WhatsApp was acquired by Facebook in the past, which makes it less credible, but its non-Facebook roots as well as the status of the most widely-spread messaging service were the only reasons to add it to the table.
Talking of ICQ, it wasn't included, in particular, for few reasons: it has relatively small userbase, it's a product of Mail.Ru group (again privacy concerns).
